services:
  shop:
    build:
      context: "."
      dockerfile: "dockerfile"
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public"
      JWT_SECRET: "${JWT_SECRET}"
      PORT: "3000"
    ports:
      - "3000:3000"
    depends_on:
      - "postgres"

  postgres:
    image: "postgres"
    restart: "always"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
    ports:
      - "5432:5432"
