name: Integration

on: [push]

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm audit --audit-level high

  verify:
    name: Verify
    needs: [audit]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 20
      - run: npm ci
      - run: npm run verify

  unit-tests:
    name: Unit Tests
    needs: [audit]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 20
      - run: npm ci
      - run: npm run build
      - run: npm run test:unit

  integration-tests:
    name: Integration Tests
    needs: [audit]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 20
      - run: docker compose up --detach
      - run: npm ci
      - run: npm run migrate
      - run: npm run seed
      - run: npm run test:integration
